Repository WillCodeForCats/solaredge-modbus-multi, pull requests merged in 2022-12, with the labels that each got.

#203 Allow command delay up to 60 seconds
  custom_components/solaredge_modbus_multi/config_flow.py
Labels: update

#209 Update translations
  custom_components/solaredge_modbus_multi/strings.json
  custom_components/solaredge_modbus_multi/translations/de.json
  custom_components/solaredge_modbus_multi/translations/en.json
  custom_components/solaredge_modbus_multi/translations/nb.json
  custom_components/solaredge_modbus_multi/translations/nl.json
  custom_components/solaredge_modbus_multi/translations/pl.json
Labels: update

#212 ChangeConfDefaultFlag enum type
  custom_components/solaredge_modbus_multi/__init__.py
  custom_components/solaredge_modbus_multi/config_flow.py
  custom_components/solaredge_modbus_multi/const.py
Labels: bug

#213 Create fr.json
  custom_components/solaredge_modbus_multi/translations/fr.json
Labels: enhancement

#171 Home assistant core 2022.11
  custom_components/solaredge_modbus_multi/number.py
  custom_components/solaredge_modbus_multi/sensor.py
  hacs.json
Labels: update
