Repository WillCodeForCats/solaredge-modbus-multi, pull requests merged in 2022-11, with the labels that each got.

#148 Qualify no response vs. no address
  custom_components/solaredge_modbus_multi/hub.py
Labels: bug

#133 Add support for storedge control
  custom_components/solaredge_modbus_multi/__init__.py
  custom_components/solaredge_modbus_multi/const.py
  custom_components/solaredge_modbus_multi/hub.py
  custom_components/solaredge_modbus_multi/number.py
  custom_components/solaredge_modbus_multi/select.py
Labels: enhancement

#158 Updates and fixes for PR #133
  custom_components/solaredge_modbus_multi/hub.py
  custom_components/solaredge_modbus_multi/number.py
  custom_components/solaredge_modbus_multi/select.py
Labels: bug, enhancement, update

#160 Remove disconnect call after write
  custom_components/solaredge_modbus_multi/hub.py
Labels: bug

#152 Add Synergy MMPPT Events sensor
  custom_components/solaredge_modbus_multi/hub.py
  custom_components/solaredge_modbus_multi/sensor.py
Labels: enhancement

#164 Bump pymodbus to 3.0.1
  custom_components/solaredge_modbus_multi/manifest.json
  requirements.txt
Labels: update

#170 Bump pymodbus to 3.0.2
  custom_components/solaredge_modbus_multi/manifest.json
  requirements.txt
Labels: bug

#177 Option for battery energy to reset to zero
  custom_components/solaredge_modbus_multi/__init__.py
  custom_components/solaredge_modbus_multi/config_flow.py
  custom_components/solaredge_modbus_multi/const.py
  custom_components/solaredge_modbus_multi/hub.py
  custom_components/solaredge_modbus_multi/sensor.py
  custom_components/solaredge_modbus_multi/strings.json
  custom_components/solaredge_modbus_multi/translations/de.json
  custom_components/solaredge_modbus_multi/translations/en.json
  custom_components/solaredge_modbus_multi/translations/nb.json
  custom_components/solaredge_modbus_multi/translations/nl.json
  custom_components/solaredge_modbus_multi/translations/pl.json
Labels: update

#178 Add battery power save mode
  custom_components/solaredge_modbus_multi/const.py
Labels: update

#181 Update meter related names
  custom_components/solaredge_modbus_multi/const.py
  custom_components/solaredge_modbus_multi/number.py
Labels: update

#182 Meter event bits as attribute
  custom_components/solaredge_modbus_multi/sensor.py
Labels: enhancement

#173 Power control UI updates
  custom_components/solaredge_modbus_multi/__init__.py
  custom_components/solaredge_modbus_multi/config_flow.py
  custom_components/solaredge_modbus_multi/const.py
  custom_components/solaredge_modbus_multi/hub.py
  custom_components/solaredge_modbus_multi/number.py
  custom_components/solaredge_modbus_multi/select.py
  custom_components/solaredge_modbus_multi/strings.json
  custom_components/solaredge_modbus_multi/translations/de.json
  custom_components/solaredge_modbus_multi/translations/en.json
  custom_components/solaredge_modbus_multi/translations/nb.json
  custom_components/solaredge_modbus_multi/translations/nl.json
  custom_components/solaredge_modbus_multi/translations/pl.json
  doc/storedge_charge_discharge_profile_programming.pdf
Labels: update

#188 Updates for limit controls
  custom_components/solaredge_modbus_multi/hub.py
  custom_components/solaredge_modbus_multi/number.py
  custom_components/solaredge_modbus_multi/select.py
  custom_components/solaredge_modbus_multi/switch.py
Labels: update

#193 Fix for inverters without limit control
  custom_components/solaredge_modbus_multi/hub.py
Labels: bug

#198 Add batt energy reset option to validation logic
  custom_components/solaredge_modbus_multi/sensor.py
Labels: update

#201 Add integration_type to manifest
  custom_components/solaredge_modbus_multi/manifest.json
Labels: update
